// Generated by gencpp from file kuka_controller/ForceData.msg
// DO NOT EDIT!


#ifndef KUKA_CONTROLLER_MESSAGE_FORCEDATA_H
#define KUKA_CONTROLLER_MESSAGE_FORCEDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kuka_controller
{
template <class ContainerAllocator>
struct ForceData_
{
  typedef ForceData_<ContainerAllocator> Type;

  ForceData_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , Mx(0.0)
    , My(0.0)
    , Mz(0.0)  {
    }
  ForceData_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , Mx(0.0)
    , My(0.0)
    , Mz(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _Mx_type;
  _Mx_type Mx;

   typedef float _My_type;
  _My_type My;

   typedef float _Mz_type;
  _Mz_type Mz;





  typedef boost::shared_ptr< ::kuka_controller::ForceData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuka_controller::ForceData_<ContainerAllocator> const> ConstPtr;

}; // struct ForceData_

typedef ::kuka_controller::ForceData_<std::allocator<void> > ForceData;

typedef boost::shared_ptr< ::kuka_controller::ForceData > ForceDataPtr;
typedef boost::shared_ptr< ::kuka_controller::ForceData const> ForceDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuka_controller::ForceData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuka_controller::ForceData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuka_controller::ForceData_<ContainerAllocator1> & lhs, const ::kuka_controller::ForceData_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.Mx == rhs.Mx &&
    lhs.My == rhs.My &&
    lhs.Mz == rhs.Mz;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuka_controller::ForceData_<ContainerAllocator1> & lhs, const ::kuka_controller::ForceData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuka_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kuka_controller::ForceData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuka_controller::ForceData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_controller::ForceData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_controller::ForceData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_controller::ForceData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_controller::ForceData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuka_controller::ForceData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c115518ba289f3faa6ed19329fa3a279";
  }

  static const char* value(const ::kuka_controller::ForceData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc115518ba289f3faULL;
  static const uint64_t static_value2 = 0xa6ed19329fa3a279ULL;
};

template<class ContainerAllocator>
struct DataType< ::kuka_controller::ForceData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuka_controller/ForceData";
  }

  static const char* value(const ::kuka_controller::ForceData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuka_controller::ForceData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 Mx\n"
"float32 My\n"
"float32 Mz\n"
;
  }

  static const char* value(const ::kuka_controller::ForceData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuka_controller::ForceData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.Mx);
      stream.next(m.My);
      stream.next(m.Mz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ForceData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuka_controller::ForceData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuka_controller::ForceData_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "Mx: ";
    Printer<float>::stream(s, indent + "  ", v.Mx);
    s << indent << "My: ";
    Printer<float>::stream(s, indent + "  ", v.My);
    s << indent << "Mz: ";
    Printer<float>::stream(s, indent + "  ", v.Mz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUKA_CONTROLLER_MESSAGE_FORCEDATA_H
