// Generated by gencpp from file kuka_controller/KukaControl.msg
// DO NOT EDIT!


#ifndef KUKA_CONTROLLER_MESSAGE_KUKACONTROL_H
#define KUKA_CONTROLLER_MESSAGE_KUKACONTROL_H

#include <ros/service_traits.h>


#include <kuka_controller/KukaControlRequest.h>
#include <kuka_controller/KukaControlResponse.h>


namespace kuka_controller
{

struct KukaControl
{

typedef KukaControlRequest Request;
typedef KukaControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct KukaControl
} // namespace kuka_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kuka_controller::KukaControl > {
  static const char* value()
  {
    return "ed9dd79fb8a5d0474ef3928715b2e454";
  }

  static const char* value(const ::kuka_controller::KukaControl&) { return value(); }
};

template<>
struct DataType< ::kuka_controller::KukaControl > {
  static const char* value()
  {
    return "kuka_controller/KukaControl";
  }

  static const char* value(const ::kuka_controller::KukaControl&) { return value(); }
};


// service_traits::MD5Sum< ::kuka_controller::KukaControlRequest> should match
// service_traits::MD5Sum< ::kuka_controller::KukaControl >
template<>
struct MD5Sum< ::kuka_controller::KukaControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kuka_controller::KukaControl >::value();
  }
  static const char* value(const ::kuka_controller::KukaControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuka_controller::KukaControlRequest> should match
// service_traits::DataType< ::kuka_controller::KukaControl >
template<>
struct DataType< ::kuka_controller::KukaControlRequest>
{
  static const char* value()
  {
    return DataType< ::kuka_controller::KukaControl >::value();
  }
  static const char* value(const ::kuka_controller::KukaControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kuka_controller::KukaControlResponse> should match
// service_traits::MD5Sum< ::kuka_controller::KukaControl >
template<>
struct MD5Sum< ::kuka_controller::KukaControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kuka_controller::KukaControl >::value();
  }
  static const char* value(const ::kuka_controller::KukaControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuka_controller::KukaControlResponse> should match
// service_traits::DataType< ::kuka_controller::KukaControl >
template<>
struct DataType< ::kuka_controller::KukaControlResponse>
{
  static const char* value()
  {
    return DataType< ::kuka_controller::KukaControl >::value();
  }
  static const char* value(const ::kuka_controller::KukaControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KUKA_CONTROLLER_MESSAGE_KUKACONTROL_H
