// Generated by gencpp from file kuka_controller/KukaControlRequest.msg
// DO NOT EDIT!


#ifndef KUKA_CONTROLLER_MESSAGE_KUKACONTROLREQUEST_H
#define KUKA_CONTROLLER_MESSAGE_KUKACONTROLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kuka_controller
{
template <class ContainerAllocator>
struct KukaControlRequest_
{
  typedef KukaControlRequest_<ContainerAllocator> Type;

  KukaControlRequest_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , a(0.0)
    , b(0.0)
    , c(0.0)  {
    }
  KukaControlRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , a(0.0)
    , b(0.0)
    , c(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _a_type;
  _a_type a;

   typedef float _b_type;
  _b_type b;

   typedef float _c_type;
  _c_type c;





  typedef boost::shared_ptr< ::kuka_controller::KukaControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuka_controller::KukaControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct KukaControlRequest_

typedef ::kuka_controller::KukaControlRequest_<std::allocator<void> > KukaControlRequest;

typedef boost::shared_ptr< ::kuka_controller::KukaControlRequest > KukaControlRequestPtr;
typedef boost::shared_ptr< ::kuka_controller::KukaControlRequest const> KukaControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuka_controller::KukaControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuka_controller::KukaControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuka_controller::KukaControlRequest_<ContainerAllocator1> & lhs, const ::kuka_controller::KukaControlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.a == rhs.a &&
    lhs.b == rhs.b &&
    lhs.c == rhs.c;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuka_controller::KukaControlRequest_<ContainerAllocator1> & lhs, const ::kuka_controller::KukaControlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuka_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kuka_controller::KukaControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuka_controller::KukaControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_controller::KukaControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_controller::KukaControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_controller::KukaControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_controller::KukaControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuka_controller::KukaControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3c35c90d64b9eb27dd8deddce8e5470";
  }

  static const char* value(const ::kuka_controller::KukaControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3c35c90d64b9eb2ULL;
  static const uint64_t static_value2 = 0x7dd8deddce8e5470ULL;
};

template<class ContainerAllocator>
struct DataType< ::kuka_controller::KukaControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuka_controller/KukaControlRequest";
  }

  static const char* value(const ::kuka_controller::KukaControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuka_controller::KukaControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 a\n"
"float32 b\n"
"float32 c\n"
;
  }

  static const char* value(const ::kuka_controller::KukaControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuka_controller::KukaControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.a);
      stream.next(m.b);
      stream.next(m.c);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KukaControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuka_controller::KukaControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuka_controller::KukaControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "a: ";
    Printer<float>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<float>::stream(s, indent + "  ", v.b);
    s << indent << "c: ";
    Printer<float>::stream(s, indent + "  ", v.c);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUKA_CONTROLLER_MESSAGE_KUKACONTROLREQUEST_H
